name: Close Stale Issues

on:
  schedule:
    - cron: "30 1 * * *" # Run every day at 1:30 AM

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: windows-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity."
          days-before-stale: 60
          days-before-close: 7
